### ISSUE TITLE
unhashable type: 'Topic'

### ISSUE THREAD

**Issue by mganske** [ehooo/django_mqtt#17]
Hi,

I am using Django 3.1.1 and Python 3.7.

When I try to delete a topic, I get this Error:

### TypeError at /admin/django_mqtt/topic/3/delete/
**unhashable type:** 'Topic'
**Request Method:**  GET
**Request URL:**	http://127.0.0.1:8000/admin/django_mqtt/topic/3/delete/
**Django Version:**	3.1.1
**Exception Type:**	TypeError
**Exception Value:** unhashable type: 'Topic'

**Comment by ehooo** [comment]
Hi @mganske thanks for the comment.
Could you add the traceback?
Regards

**Comment by mganske** [comment]
Sure.

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/django_mqtt/topic/2/delete/

Django Version: 3.1.1
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'accesscontrol',
 'django_mqtt',
 'django_mqtt.mosquitto.auth_plugin',
 'django_mqtt.publisher']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1846, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1867, in _delete_view
    deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1841, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/utils.py", line 118, in get_deleted_objects
    collector.collect(objs)
  File "/home/huegel/Uni/Bachelor/SS20/Bachelorarbeit/werkstatt3/venv/lib/python3.7/site-packages/django/contrib/admin/utils.py", line 179, in collect
    self.model_objs[obj._meta.model].add(obj)

Exception Type: TypeError at /admin/django_mqtt/topic/2/delete/
Exception Value: unhashable type: 'Topic'
```
